name: scanpro
description: ScanPro - Secure System Scanner with EULA
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
